name: Update PetKit Record
on:
  push:
      branches:
        - master
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '*/15 * * * *'

jobs:
  Update-Records-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Build venv
        run: tox -e venv
      - name: Run script
        env:
            AUTH_JSON: ${{ secrets.AUTH_JSON }}
            PETKIT_PASSWORD: ${{ secrets.PETKIT_PASSWORD }}
            PETKIT_USERNAME: ${{ secrets.PETKIT_USERNAME }}
            SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run:  venv/bin/python -m script.update
